#application: campwise-achievements-hrd
application: campwise-achievements-sandbox
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets
  login: admin

- url: /js
  static_dir: js
  login: admin

- url: /images
  static_dir: images
  login: admin

- url: /.*
  script: main.app
  login: admin
