application: campwise-achievements-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  login: admin

- url: /.*
  script: main.app
  login: admin
