#instead use --project and --version flag on gcloud command
#application: campwise-achievements-hrd
#application: campwise-achievements-sandbox
#version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /stylesheets
  static_dir: stylesheets
  login: admin
  secure: always

- url: /js
  static_dir: js
  login: admin
  secure: always

- url: /images
  static_dir: images
  login: admin
  secure: always

- url: /.*
  script: main.app
  login: admin
  secure: always
